export const imageDB = {
  sample2: require("../assets/imageset/coupone.png"),
  splash: require("../assets/imageset/splashscreen.png"),
  logo: require("../assets/imageset/logo.png"),
  gps: require("../assets/imageset/gps.png"),
  prev: require("../assets/imageset/prev.png"),
  right: require("../assets/imageset/right.png"),
  bell: require("../assets/imageset/bell.png"),
  setting: require("../assets/imageset/setting.png"),
  loading: require("../assets/imageset/loading.gif"),
  search: require("../assets/imageset/search.png"),
  refresh: require("../assets/imageset/refresh.png"),
  thema: require("../assets/imageset/thema.png"),
  coupone: require("../assets/imageset/coupone.png"),
  type: require("../assets/imageset/type.png"),
  like: require("../assets/imageset/like.png"),
  price: require("../assets/imageset/price.png"),
  close: require("../assets/imageset/close.png"),
  heart: require("../assets/imageset/heart.png"),
  hearton: require("../assets/imageset/hearton.png"),
  question: require("../assets/imageset/question.png"),
  kakaomsg: require("../assets/imageset/kakaomsg.png"),
  navermsg: require("../assets/imageset/navermsg.png"),
  bottom_home: require("../assets/imageset/bottom_home.png"),
  bottom_home_disable: require("../assets/imageset/bottom_home_disable.png"),
  bottom_location: require("../assets/imageset/bottom_location.png"),
  bottom_location_disable: require("../assets/imageset/bottom_location_disable.png"),
  bottom_gps: require("../assets/imageset/bottom_gps.png"),
  bottom_chat: require("../assets/imageset/bottom_chat.png"),
  bottom_chat_disable: require("../assets/imageset/bottom_chat_disable.png"),
  bottom_profile: require("../assets/imageset/bottom_profile.png"),
  bottom_profile_disable: require("../assets/imageset/bottom_profile_disable.png"),
  check_recommend: require("../assets/imageset/recommend.png"),
  FilterKorea: require("../assets/imageset/filter_korea.png"),
  FilterChina: require("../assets/imageset/filter_china.png"),
  FilterTileland: require("../assets/imageset/filter_tailand.png"),
  FilterOneshop: require("../assets/imageset/filter_oneshop.png"),
  FilterWacksing: require("../assets/imageset/filter_wacksing.png"),
  FilterMeridian: require("../assets/imageset/filter_Meridian.png"),
  FilterAroma: require("../assets/imageset/filter_aroma.png"),
  FilterSports: require("../assets/imageset/filter_sports.png"),
  FilterSwedish: require("../assets/imageset/filter_swedish.png"),
  FilterFoot: require("../assets/imageset/filter_foot.png"),
  FilterCoupone: require("../assets/imageset/filter_coupone.png"),
  FilterNewStore: require("../assets/imageset/filter_newstore.png"),
  FilterRanking: require("../assets/imageset/filter_ranking.png"),
  ThemaWoman: require("../assets/imageset/thema_woman.png"),
  ThemaMan: require("../assets/imageset/thema_man.png"),
  Thema20: require("../assets/imageset/thema_20.png"),
  Thema30: require("../assets/imageset/thema_30.png"),
  Thema40: require("../assets/imageset/thema_40.png"),
  ThemaCar: require("../assets/imageset/thema_car.png"),
  ThemaSleep: require("../assets/imageset/thema_sleep.png"),
  ThemaShower: require("../assets/imageset/thema_shower.png"),
  ThemaOneshop: require("../assets/imageset/thema_oneshop.png"),
  ThemaGroups: require("../assets/imageset/thema_groups.png"),
  ThemaCouple: require("../assets/imageset/thema_couple.png"),
  ThemaGroup: require("../assets/imageset/thema_group.png"),
  ThemaManOnly: require("../assets/imageset/thema_manonly.png"),
  ThemaWomanOnly: require("../assets/imageset/thema_womanonly.png"),
  ThemaComman: require("../assets/imageset/thema_common.png"),
  NavigationImage: require("../assets/imageset/navigation.png"),
  ReviewImage: require("../assets/imageset/review.png"),
  HeartImage: require("../assets/imageset/heart.png"),
  Address: require("../assets/imageset/addr.png"),
  Watch: require("../assets/imageset/watch.png"),
  Car: require("../assets/imageset/car.png"),
  Tel: require("../assets/imageset/tel.png"),
  Up: require("../assets/imageset/up.png"),
  Prev_White: require("../assets/imageset/prev_white.png"),
  Home: require("../assets/imageset/home.png"),
  STORE: require("../assets/imageset/store.png"),
  Massage: require("../assets/imageset/massage.png"),
  Heart_White: require("../assets/imageset/heart_white.png"),
  marone_person: require("../assets/imageset/maroneperson.png"),
  Progress: require("../assets/imageset/tranparentprogress.gif"),
  Profile:
    "https://firebasestorage.googleapis.com/v0/b/marone-d7e06.appspot.com/o/images%2Fprofile4040.png?alt=media&token=465b3bdd-bb9b-4344-8129-7a5cd98c57d5",
  basic: require("../assets/imageset/basic.png"),
  coupon: require("../assets/imageset/coupon.png"),
  sample: require("../assets/imageset/sample.png"),
  sample2: require("../assets/imageset/sample2.png"),
  sample3: require("../assets/imageset/sample3.png"),
  banner1: require("../assets/imageset/banner1.png"),
  banner2: require("../assets/imageset/banner2.png"),
  checksample1 : require("../assets/imageset/checksample1.png"),
  checksample2 : require("../assets/imageset/checksample2.png"),
  checksample3 : require("../assets/imageset/checksample3.png"),
  checksample4 : require("../assets/imageset/checksample4.png"),
  checksample5 : require("../assets/imageset/checksample5.png"),
  checksample6 : require("../assets/imageset/checksample6.png"),
  checksample7 : require("../assets/imageset/checksample7.png"),
  maroneperson2: require("../assets/imageset/maroneperson2.png"),
  maroneperson: require("../assets/imageset/maroneperson.png"),
  roomsample1: require("../assets/imageset/roomsample1.png"),
  roomsample2: require("../assets/imageset/roomsample2.png"),
  alarm: require("../assets/imageset/alarm.png"),
  insurance: require("../assets/imageset/insurance.png"),
  card: require("../assets/imageset/card.png"),
  woman: require("../assets/imageset/woman.png"),
  loadbox1: require("../assets/imageset/loadbox1.png"),
  loadbox2: require("../assets/imageset/loadbox2.png"),
  loadbox3: require("../assets/imageset/loadbox3.png"),
  loadbox4: require("../assets/imageset/loadbox4.png"),
  loadbox5: require("../assets/imageset/loadbox5.png"),
  loadprofit: require("../assets/imageset/loadprofit.png"),
  advertise1: require("../assets/imageset/advertise1.png"),
  advertise2: require("../assets/imageset/advertise2.png"),
  advertise3: require("../assets/imageset/advertise3.png"),
  success: require("../assets/imageset/success.gif"),
  fail: require("../assets/imageset/fail.gif"),
  medal: require("../assets/imageset/medal.png"),
  license1: require("../assets/imageset/license1.png"),
  license2: require("../assets/imageset/license2.png"),
  nation1: require("../assets/imageset/nation1.png"),
  nation2: require("../assets/imageset/nation2.png"),
  group1 : require("../assets/imageset/groupsample1.png"),
  group2 : require("../assets/imageset/groupsample2.png"),
  group3 : require("../assets/imageset/groupsample3.png"),
  group4 : require("../assets/imageset/groupsample4.png"),
  group5 : require("../assets/imageset/groupsample5.png"),
  group6 : require("../assets/imageset/groupsample6.png"),
  communitylist1 : require("../assets/imageset/communitylist1.png"),
  communitylist2 : require("../assets/imageset/communitylist2.png"),
  communitylist3 : require("../assets/imageset/communitylist3.png"),
  communitylist4 : require("../assets/imageset/communitylist4.png"),
  communitylist5 : require("../assets/imageset/communitylist5.png"),
  communitylist6 : require("../assets/imageset/communitylist6.png"),
  communitylist7 : require("../assets/imageset/communitylist7.png"),
  communitylist8 : require("../assets/imageset/communitylist8.png"),
  communitylist9 : require("../assets/imageset/communitylist9.png"),
  communitylist10 : require("../assets/imageset/communitylist10.png"),
  communitylist11: require("../assets/imageset/communitylist11.png"),
  communitylist12 : require("../assets/imageset/communitylist12.png"),
  communitylist13 : require("../assets/imageset/communitylist13.png"),
  loadding2: require("../assets/imageset/loading2.gif"),
  event1 : require("../assets/imageset/event1.png"),
  event2 : require("../assets/imageset/event2.png"),
  event3 : require("../assets/imageset/event3.png"),
  guidesample : require("../assets/imageset/guidesample.png")

};



